name: Cleanup old files

on:
  schedule:
    - cron: "0 0 */3 * *"

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Delete old folders in docs (older than 7 days)
        run: |
          cd docs
          find . -mindepth 1 -maxdepth 1 -type d -mtime +7 -exec rm -rf {} +

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Cleanup old folders older than 7 days" || echo "No changes"
          git push