name: FCE

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
      track:
        required: false

env:
  URL: ${{ github.event.inputs.url }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
  FCE:
    name: ${{ github.event.inputs.track }}
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v4  

      - name: cache  
        id: cache  
        uses: actions/cache@v4  
        with:  
          path: |  
            ~/.local/lib/python3*/site-packages  
            tools  
          key: ${{ runner.os }}-cache-${{ hashFiles('**/tools/*') }}  
          restore-keys: |  
            ${{ runner.os }}-cache-  

      - name: install  
        if: steps.cache.outputs.cache-hit != 'true'  
        run: |  
          if [ ! -d tools ]; then  
            sudo apt-get update && sudo apt-get install -y python3-pip p7zip-full aria2  
            git clone https://github.com/vm03/payload_dumper.git tools  
            aria2c -o erofs-utils.zip https://github.com/sekaiacg/erofs-utils/releases/download/v1.8.1-240810/erofs-utils-v1.8.1-gddbed144-Linux_x86_64-2408101422.zip  
            7z x erofs-utils.zip -otools  
            pip install -r ./tools/requirements.txt  
            rm -f erofs-utils.zip  
          fi  

      - name: download  
        run: |  
          aria2c -x 7 -s 7 -k 1M --continue --max-tries=0 --log=LOG --out='exrom.zip' "$URL"  
          7z x exrom.zip -o./  
          rm exrom.zip  

      - name: EC  
        run: |
          
          boot_img="false"
          init_boot="false"
          vendor_boot="false"

          if [ -f "payload.bin" ]; then
            echo "payload.bin found, extracting images..."
            for img in boot init_boot vendor_boot; do
              echo "Attempting to extract $img..."
              ./tools/payload_dumper.py --out . --images $img payload.bin || echo "$img not found in payload.bin, skipping..."
            done
          else
            echo "payload.bin not found, using existing images..."
          fi

          rom_name=$(basename "$URL" .zip)
          TELEGRAM_API="https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument"

          BOOT_CHAT_ID="-1002613796115"
          INIT_BOOT_CHAT_ID="-1002487209290"
          VENDOR_BOOT_CHAT_ID="-1002551940450"

          for img in boot init_boot vendor_boot; do
            if [ -f "$img.img" ]; then
              7z a "${img}_img_${rom_name}.zip" "$img.img"
            else
              echo "$img.img not found, skipping..."
            fi
          done

          if [ -f "boot_img_${rom_name}.zip" ]; then
            curl -F chat_id="$BOOT_CHAT_ID" \
                 -F document=@"boot_img_${rom_name}.zip" \
                 -F caption="$rom_name" \
                 "$TELEGRAM_API"
            boot_img="true"
          fi

          if [ -f "init_boot_img_${rom_name}.zip" ]; then
            curl -F chat_id="$INIT_BOOT_CHAT_ID" \
                 -F document=@"init_boot_img_${rom_name}.zip" \
                 -F caption="$rom_name" \
                 "$TELEGRAM_API"
            init_boot="true"
          fi

          if [ -f "vendor_boot_img_${rom_name}.zip" ]; then
            curl -F chat_id="$VENDOR_BOOT_CHAT_ID" \
                 -F document=@"vendor_boot_img_${rom_name}.zip" \
                 -F caption="$rom_name" \
                 "$TELEGRAM_API"
            vendor_boot="true"
          fi

          FILE="v.json"
          NEW_ENTRY='"'$rom_name'": {
            "boot_img_zip": "'$boot_img'",
            "init_boot_img_zip": "'$init_boot'",
            "vendor_boot_img_zip": "'$vendor_boot'"
          }'

          if [ ! -f "$FILE" ]; then
            echo -e "{\n$NEW_ENTRY\n}" > "$FILE"
          else
            sed -i '$d' "$FILE"
            echo -e ",\n$NEW_ENTRY\n}" >> "$FILE"
          fi

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add v.json
          git commit -m "update v.json with $rom_name"
          git push

          echo "boot_img=$boot_img" >> output.env
          echo "init_boot=$init_boot" >> output.env
          echo "vendor_boot=$vendor_boot" >> output.env

      - name: End of process
        run: |
          set -a
          source output.env
          set +a

          if [ "$boot_img" = "true" ]; then
            echo "boot.img has been sent."
          else
            echo "boot.img is not available in this ROM."
          fi

          if [ "$init_boot" = "true" ]; then
            echo "init_boot.img has been sent."
          else
            echo "init_boot.img is not available in this ROM."
          fi

          if [ "$vendor_boot" = "true" ]; then
            echo "vendor_boot.img has been sent."
          else
            echo "vendor_boot.img is not available in this ROM."
          fi